server:
  port: 8090

spring:
  application:
    name: account-service

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:e-bank
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
